apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: year4-project-dev
type: Opaque
stringData:
  DB_HOST: localhost
  DB_USER: dev_user
  DB_PASSWORD: dev_password
  DB_NAME: year4_dev
  API_KEY: dev-api-key-12345
  AWS_ACCESS_KEY_ID: dev-access-key
  AWS_SECRET_ACCESS_KEY: dev-secret-key
  ELASTICSEARCH_URL: http://quickstart-es-http.elastic-system.svc.cluster.local:9200
  ELASTICSEARCH_USER: elastic
  ELASTICSEARCH_PASSWORD: changeme
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: year4-project-dev
type: Opaque
stringData:
  REDIS_HOST: redis.year4-project-dev.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "dev-redis-password"
  REDIS_DB: "0"
  ADMIN_BL_REDIS_URL: "asd" 
  CUSTOMER_BL_REDIS_URL: "asd"
  JOB_BL_REDIS_URL: "asd"
  MAPS_REDIS_URL: "asd"
  AUTH_REDIS_URL : "asd"
  USER_BL_REDIS_URL : "asd"

---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: year4-project-dev
type: Opaque
stringData:
  DB_HOST: localhost
  DB_USER: dev_user
  DB_PASSWORD: dev_password
  DB_NAME: year4_dev
  DATABASE_URL : postgres://dev_user:dev_password@localhost:5432/year4_dev
---
apiVersion: v1
kind: Secret
metadata:
  name: google-maps-secrets
  namespace: year4-project-dev
type: Opaque
stringData:
  GOOGLE_MAPS_API_KEY: dev-google-maps-api-key-12345
  GOOGLE_MAPS_SERVER_KEY : dev-google-maps-server-key-12345
  GOOGLE_MAPS_BROWSER_KEY : dev-google-maps-browser-key-12345
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secrets
  namespace: year4-project-dev
type: Opaque
stringData:
  SMTP_HOST: smtp.dev-email.com
  SMTP_PORT: "587"
  SMTP_USER: dev_email_user
  SMTP_PASSWORD: dev_email_password