apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: year4-project-service-mesh-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: year4-project-production
  source:
    repoURL: https://gitlab.comp.dkit.ie/finalproject/Prototypes/yr4-projectdeploymentrepo.git
    targetRevision: main
    path: kubernetes/service-mesh/production
  destination:
    server: https://kubernetes.default.svc
    namespace: year4-project
  ignoreDifferences:
    - group: networking.istio.io
      kind: VirtualService
      jqPathExpressions:
        - .spec.http[].route[].weight
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true