apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: year4-project-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: year4-project-production
  source:
    repoURL: https://gitlab.comp.dkit.ie/finalproject/Prototypes/yr4-projectdeploymentrepo.git
    targetRevision: main
    path: kubernetes/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: year4-project
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true