apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: year4-project-production
  namespace: argocd
spec:
  description: Year 4 project production GitOps application
  sourceRepos:
    - https://gitlab.comp.dkit.ie/finalproject/Prototypes/yr4-projectdeploymentrepo.git
  destinations:
    - namespace: year4-project
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: scheduling.k8s.io
      kind: PriorityClass
    - group: external-secrets.io
      kind: ClusterSecretStore
    - group: cert-manager.io
      kind: ClusterIssuer
  namespaceResourceWhitelist:
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: apps
      kind: Deployment
    - group: batch
      kind: Job
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: policy
      kind: PodDisruptionBudget
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: external-secrets.io
      kind: ExternalSecret
    - group: argoproj.io
      kind: Rollout
    - group: argoproj.io
      kind: AnalysisTemplate
    - group: networking.istio.io
      kind: Gateway
    - group: networking.istio.io
      kind: VirtualService
    - group: networking.istio.io
      kind: DestinationRule
    - group: networking.istio.io
      kind: ServiceEntry
    - group: security.istio.io
      kind: PeerAuthentication
    - group: security.istio.io
      kind: AuthorizationPolicy
    - group: telemetry.istio.io
      kind: Telemetry
    - group: monitoring.coreos.com
      kind: PodMonitor
    - group: monitoring.coreos.com
      kind: ServiceMonitor