apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - peer-authentication.yaml
  - telemetry.yaml
  - destination-rules.yaml
  - serviceentries-external-apis.yaml
  - authorization-policy-audit.yaml
  - ingress-gateway.yaml
  - virtualservice-nginx-gateway.yaml
  - virtualservices-rollout-services.yaml
  - podmonitor-istio-proxies.yaml
  - servicemonitor-istiod.yaml

patches:
  - target:
      group: networking.istio.io
      version: v1beta1
      kind: VirtualService
    patch: |-
      - op: add
        path: /spec/http/0/timeout
        value: 10s