meshConfig:
  enablePrometheusMerge: true
  defaultConfig:
    holdApplicationUntilProxyStarts: true
pilot:
  autoscaleMin: 2
  autoscaleMax: 5
  cni:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 768Mi
global:
  priorityClassName: year4-mesh-critical
  proxy:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi