fullnameOverride: kiali
auth:
  strategy: anonymous
deployment:
  cluster_wide_access: false
  accessible_namespaces:
    - istio-system
    - monitoring
    - year4-project-staging
    - year4-project
  discovery_selectors:
    default:
      - matchLabels:
          kubernetes.io/metadata.name: istio-system
      - matchLabels:
          kubernetes.io/metadata.name: monitoring
      - matchLabels:
          app.kubernetes.io/part-of: year4-project
  view_only_mode: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
external_services:
  grafana:
    enabled: true
    in_cluster_url: http://monitoring-grafana.monitoring:80
    url: http://localhost:3000
    health_check_url: http://monitoring-grafana.monitoring:80/api/health
    auth:
      type: none
      use_kiali_token: false
  prometheus:
    url: http://kube-prometheus-stack-prometheus.monitoring:9090
istio_namespace: istio-system
kiali_feature_flags:
  validations:
    ignore:
      - KIA1301
      - KIA1317