fullnameOverride: kiali
auth:
  strategy: anonymous
deployment:
  accessible_namespaces:
    - "**"
  view_only_mode: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
external_services:
  grafana:
    enabled: true
    in_cluster_url: http://monitoring-grafana.monitoring:80
    url: http://localhost:3000
    health_check_url: http://monitoring-grafana.monitoring:80/api/health
    auth:
      type: none
      use_kiali_token: false
  prometheus:
    url: http://kube-prometheus-stack-prometheus.monitoring:9090
istio_namespace: istio-system