fullnameOverride: kiali
auth:
  strategy: anonymous
deployment:
  accessible_namespaces:
    - "**"
  view_only_mode: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
external_services:
  prometheus:
    url: http://kube-prometheus-stack-prometheus.monitoring:9090
istio_namespace: istio-system