fullnameOverride: kube-prometheus-stack

commonLabels:
  environment: production
  app.kubernetes.io/part-of: year4-project-observability

crds:
  enabled: true

alertmanager:
  enabled: false

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: 2d
    retentionSize: 8GB
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 700m
        memory: 1536Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  resources:
    requests:
      cpu: 75m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 384Mi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

kubelet:
  enabled: true

kubeApiServer:
  enabled: true

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: true

coreDns:
  enabled: true

grafana:
  enabled: true
  replicas: 1
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  defaultDashboardsEnabled: true
  persistence:
    enabled: true
    type: pvc
    storageClassName: gp3
    accessModes:
      - ReadWriteOnce
    size: 5Gi
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      defaultDatasourceUid: prometheus
  resources:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 512Mi

defaultRules:
  create: true
  rules:
    alertmanager: false
    etcd: false
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: true
    kubeApiserverSlos: false
    kubeControllerManager: false
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true