apiVersion: v1
kind: Service
metadata:
  name: customer-bl-service
  labels:
    app: customer-bl-service
spec:
  type: ClusterIP
  selector:
    app: customer-bl-service
  ports:
  - port: 80
    targetPort: 8007
    protocol: TCP
    name: http
  sessionAffinity: None