apiVersion: v1
kind: Service
metadata:
  name: job-db-access-service
  labels:
    app: job-db-access-service
spec:
  type: ClusterIP
  selector:
    app: job-db-access-service
  ports:
  - port: 80
    targetPort: 8003
    protocol: TCP
    name: http
  sessionAffinity: None