apiVersion: v1
kind: Service
metadata:
  name: job-bl-service
  labels:
    app: job-bl-service
spec:
  type: ClusterIP
  selector:
    app: job-bl-service
  ports:
  - port: 80
    targetPort: 8006
    protocol: TCP
    name: http
  sessionAffinity: None