apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: gateway
    service.istio.io/canonical-name: gateway
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/component: gateway
        service.istio.io/canonical-name: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: frontend
    service.istio.io/canonical-name: gateway
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/component: frontend
        service.istio.io/canonical-name: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
    service.istio.io/canonical-name: business-layer
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: business-layer
        app.kubernetes.io/component: business-logic
        service.istio.io/canonical-name: business-layer
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-bl-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
    service.istio.io/canonical-name: business-layer
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: business-layer
        app.kubernetes.io/component: business-logic
        service.istio.io/canonical-name: business-layer
---
apiVersion: v1
kind: Service
metadata:
  name: admin-bl-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-bl-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
    service.istio.io/canonical-name: business-layer
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: business-layer
        app.kubernetes.io/component: business-logic
        service.istio.io/canonical-name: business-layer
---
apiVersion: v1
kind: Service
metadata:
  name: user-bl-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-bl-service-deployment
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
    service.istio.io/canonical-name: business-layer
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: business-layer
        app.kubernetes.io/component: business-logic
        service.istio.io/canonical-name: business-layer
---
apiVersion: v1
kind: Service
metadata:
  name: job-bl-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-bl-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
    service.istio.io/canonical-name: business-layer
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: business-layer
        app.kubernetes.io/component: business-logic
        service.istio.io/canonical-name: business-layer
---
apiVersion: v1
kind: Service
metadata:
  name: customer-bl-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maps-access-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
    service.istio.io/canonical-name: business-layer
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: business-layer
        app.kubernetes.io/component: business-logic
        service.istio.io/canonical-name: business-layer
---
apiVersion: v1
kind: Service
metadata:
  name: maps-access-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
    service.istio.io/canonical-name: business-layer
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: business-layer
        app.kubernetes.io/component: business-logic
        service.istio.io/canonical-name: business-layer
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app.kubernetes.io/name: business-layer
    app.kubernetes.io/component: business-logic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db-access-service
  labels:
    app.kubernetes.io/name: database-access-layer
    app.kubernetes.io/component: database-access
    service.istio.io/canonical-name: database-access-layer
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database-access-layer
        app.kubernetes.io/component: database-access
        service.istio.io/canonical-name: database-access-layer
---
apiVersion: v1
kind: Service
metadata:
  name: user-db-access-service
  labels:
    app.kubernetes.io/name: database-access-layer
    app.kubernetes.io/component: database-access
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-db-access-service-deployment
  labels:
    app.kubernetes.io/name: database-access-layer
    app.kubernetes.io/component: database-access
    service.istio.io/canonical-name: database-access-layer
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database-access-layer
        app.kubernetes.io/component: database-access
        service.istio.io/canonical-name: database-access-layer
---
apiVersion: v1
kind: Service
metadata:
  name: job-db-access-service
  labels:
    app.kubernetes.io/name: database-access-layer
    app.kubernetes.io/component: database-access
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db-access-service
  labels:
    app.kubernetes.io/name: database-access-layer
    app.kubernetes.io/component: database-access
    service.istio.io/canonical-name: database-access-layer
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database-access-layer
        app.kubernetes.io/component: database-access
        service.istio.io/canonical-name: database-access-layer
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db-access-service
  labels:
    app.kubernetes.io/name: database-access-layer
    app.kubernetes.io/component: database-access
