apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- rbac.yaml
- cert-issuers.yaml
- auth-svc-deployment.yml
- auth-service-svc.yml
- customer-bl-service-deployment.yml
- customer-bl-service-svc.yml
- customer-db-access-service-deployment.yml
- customer-db-access-service-svc.yml
- job-bl-service-deployment.yml
- job-bl-service-svc.yml
- job-db-access-service-deployment.yml
- job-db-access-service-svc.yml
- admin-bl-service-deployment.yaml
- admin-bl-service-svc.yaml
- nginx-deployment.yaml
- nginx-service.yml
- nginx-configmap.yml
- ingress-gateway.yml
- user-bl-service-deployment.yml
- user-bl-service-svc.yml
- user-db-access-service-deployment.yml
- user-db-access-service-svc.yml
- frontend-deployment.yml
- frontend-service.yml