apiVersion: v1
kind: Service
metadata:
  name: maps-access-service
  labels:
    app: maps-access-service
spec:
  type: ClusterIP
  selector:
    app: maps-access-service
  ports:
  - port: 80
    targetPort: 8009
    protocol: TCP
    name: http
  sessionAffinity: None
