apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akeyless-secrets
spec:
  provider: akeyless
  parameters:
    objects: |
      - objectName: "/prod/db/password"
        objectType: "secret"
        objectAlias: "DB_PASSWORD"
      - objectName: "Redis_password"
        objectType: "secret"
        objectAlias: "REDIS_PASSWORD"
  secretObjects:
  - data:
    - objectKey: "DB_PASSWORD"
      key: "db-password"
    - objectKey: "REDIS_PASSWORD"
      key: "redis-password"
    secretKey: akeyless-secrets-synced
    type: Opaque