apiVersion: v1
kind: Service
metadata:
  name: user-bl-service
  labels:
    app: user-bl-service
spec:
  type: ClusterIP
  selector:
    app: user-bl-service
  ports:
  - port: 80
    targetPort: 8004
    protocol: TCP
    name: http
  sessionAffinity: None