apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: job-bl-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: job-bl-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: job-db-access-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: job-db-access-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: customer-bl-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: customer-bl-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: customer-db-access-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: customer-db-access-service