apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluent-bit.fullname" . }}
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 2020
      targetPort: http
      protocol: TCP
      name: http
    - port: 9880
      targetPort: input
      protocol: TCP
      name: input
  selector:
    {{- include "fluent-bit.selectorLabels" . | nindent 4 }}
