apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - peer-authentication.yaml
  - telemetry.yaml
  - destination-rules.yaml
  - authorization-policy-audit.yaml
  - ingress-gateway.yaml
  - virtualservice-nginx-gateway.yaml
  - podmonitor-istio-proxies.yaml
  - servicemonitor-istiod.yaml