apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxies-staging
  namespace: monitoring
  labels:
    app.kubernetes.io/name: istio-proxies
    app.kubernetes.io/part-of: year4-project
spec:
  namespaceSelector:
    matchNames:
      - year4-project-staging
      - istio-system
  selector:
    matchExpressions:
      - key: istio-prometheus-ignore
        operator: DoesNotExist
  podMetricsEndpoints:
    - interval: 30s
      path: /stats/prometheus
      port: http-envoy-prom