- op: add
  path: /spec/strategy/canary/stableService
  value: notification-service
- op: add
  path: /spec/strategy/canary/canaryService
  value: notification-service-canary
- op: add
  path: /spec/strategy/canary/trafficRouting
  value:
    istio:
      virtualService:
        name: notification-service
        routes:
          - primary
- op: add
  path: /spec/strategy/canary/analysis
  value:
    startingStep: 1
    templates:
      - templateName: istio-canary-analysis
    args:
      - name: namespace
        value: year4-project
      - name: stable-service
        value: notification-service
      - name: canary-service
        value: notification-service-canary