apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - servicemonitor-apps.yaml
  - servicemonitor-fluent-bit.yaml
  - prometheusrules-local.yaml
  - dashboard-local-overview.yaml
