#!/bin/sh
set -eu

IMAGE_VERSION="${1:-${IMAGE_VERSION:-}}"
ENVIRONMENT="${2:-}"
REPOSITORY="${IMAGE_REPOSITORY:-${IMAGE_TAG:-bencev04/4th-year-proj-tadgh-bence}}"

if [ -z "$IMAGE_VERSION" ]; then
  echo "ERROR: IMAGE_VERSION is required"
  exit 1
fi

if [ -z "$ENVIRONMENT" ]; then
  echo "usage: write-image-pins.sh <image-version|latest> <staging|production>"
  exit 1
fi

case "$ENVIRONMENT" in
  staging|production) ;;
  *)
    echo "ERROR: environment must be staging or production, got: $ENVIRONMENT"
    exit 1
    ;;
esac

if printf '%s' "$IMAGE_VERSION" | grep -q '\$'; then
  echo "ERROR: IMAGE_VERSION contains a literal dollar sign: $IMAGE_VERSION"
  exit 1
fi

if [ "$IMAGE_VERSION" != "latest" ] && ! printf '%s' "$IMAGE_VERSION" | grep -Eq '^[0-9a-f]{7,40}$'; then
  echo "ERROR: IMAGE_VERSION must be latest or a git SHA-like value, got: $IMAGE_VERSION"
  exit 1
fi

OVERLAY_DIR="kubernetes/overlays/$ENVIRONMENT"
PINS_DIR="$OVERLAY_DIR/image-pins"
LEGACY_PINS_FILE="$OVERLAY_DIR/image-pins.yaml"

if [ ! -d "$OVERLAY_DIR" ]; then
  echo "ERROR: overlay directory not found: $OVERLAY_DIR"
  exit 1
fi

tag() {
  SERVICE="$1"
  printf '%s:%s-%s' "$REPOSITORY" "$SERVICE" "$IMAGE_VERSION"
}

write_patch() {
  API_VERSION="$1"
  KIND="$2"
  RESOURCE_NAME="$3"
  CONTAINER_NAME="$4"
  SERVICE_TAG="$5"
  FILE_NAME="$6"

  cat > "$PINS_DIR/$FILE_NAME.yaml" <<EOF
# Generated by scripts/deployment/write-image-pins.sh.
# This file is committed by CI so Argo CD deploys the exact image version that passed staging.
apiVersion: $API_VERSION
kind: $KIND
metadata:
  name: $RESOURCE_NAME
spec:
  template:
    spec:
      containers:
        - name: $CONTAINER_NAME
          image: $(tag "$SERVICE_TAG")
EOF
}

mkdir -p "$PINS_DIR"
rm -f "$PINS_DIR"/*.yaml
rm -f "$LEGACY_PINS_FILE"

write_patch apps/v1 Deployment auth-service auth-service auth-service auth-service
write_patch apps/v1 Deployment user-bl-service user-bl-service user-bl-service user-bl-service
write_patch apps/v1 Deployment user-db-access-service user-db-access-service user-db-access-service user-db-access-service
write_patch apps/v1 Deployment job-bl-service-deployment job-bl-service job-bl-service job-bl-service-deployment
write_patch apps/v1 Deployment job-db-access-service-deployment job-db-access-service job-db-access-service job-db-access-service-deployment
write_patch apps/v1 Deployment customer-bl-service customer-bl-service customer-bl-service customer-bl-service
write_patch apps/v1 Deployment customer-db-access-service customer-db-access-service customer-db-access-service customer-db-access-service
write_patch apps/v1 Deployment admin-bl-service admin-bl-service admin-bl-service admin-bl-service
write_patch apps/v1 Deployment maps-access-service maps-access-service maps-access-service maps-access-service
write_patch apps/v1 Deployment notification-service notification-service notification-service notification-service
write_patch apps/v1 Deployment frontend-deployment frontend frontend frontend-deployment
write_patch apps/v1 Deployment nginx-gateway nginx nginx nginx-gateway
write_patch batch/v1 Job migration-runner migration-runner migration-runner migration-runner

echo "Wrote $PINS_DIR with $IMAGE_VERSION image pins"