#!/bin/sh
set -eu

IMAGE_VERSION="${1:-${IMAGE_VERSION:-}}"
ENVIRONMENT="${2:-}"
REPOSITORY="${IMAGE_REPOSITORY:-${IMAGE_TAG:-bencev04/4th-year-proj-tadgh-bence}}"

if [ -z "$IMAGE_VERSION" ]; then
  echo "ERROR: IMAGE_VERSION is required"
  exit 1
fi

if [ -z "$ENVIRONMENT" ]; then
  echo "usage: write-image-pins.sh <image-version|latest> <staging|production>"
  exit 1
fi

case "$ENVIRONMENT" in
  staging|production) ;;
  *)
    echo "ERROR: environment must be staging or production, got: $ENVIRONMENT"
    exit 1
    ;;
esac

if printf '%s' "$IMAGE_VERSION" | grep -q '\$'; then
  echo "ERROR: IMAGE_VERSION contains a literal dollar sign: $IMAGE_VERSION"
  exit 1
fi

if [ "$IMAGE_VERSION" != "latest" ] && ! printf '%s' "$IMAGE_VERSION" | grep -Eq '^[0-9a-f]{7,40}$'; then
  echo "ERROR: IMAGE_VERSION must be latest or a git SHA-like value, got: $IMAGE_VERSION"
  exit 1
fi

OVERLAY_DIR="kubernetes/overlays/$ENVIRONMENT"
PINS_FILE="$OVERLAY_DIR/image-pins.yaml"

if [ ! -d "$OVERLAY_DIR" ]; then
  echo "ERROR: overlay directory not found: $OVERLAY_DIR"
  exit 1
fi

tag() {
  SERVICE="$1"
  printf '%s:%s-%s' "$REPOSITORY" "$SERVICE" "$IMAGE_VERSION"
}

cat > "$PINS_FILE" <<EOF
# Generated by scripts/deployment/write-image-pins.sh.
# This file is committed by CI so Argo CD deploys the exact image version that passed staging.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth-service
          image: $(tag auth-service)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-bl-service
spec:
  template:
    spec:
      containers:
        - name: user-bl-service
          image: $(tag user-bl-service)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db-access-service
spec:
  template:
    spec:
      containers:
        - name: user-db-access-service
          image: $(tag user-db-access-service)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-bl-service-deployment
spec:
  template:
    spec:
      containers:
        - name: job-bl-service
          image: $(tag job-bl-service)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-db-access-service-deployment
spec:
  template:
    spec:
      containers:
        - name: job-db-access-service
          image: $(tag job-db-access-service)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-bl-service
spec:
  template:
    spec:
      containers:
        - name: customer-bl-service
          image: $(tag customer-bl-service)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db-access-service
spec:
  template:
    spec:
      containers:
        - name: customer-db-access-service
          image: $(tag customer-db-access-service)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-bl-service
spec:
  template:
    spec:
      containers:
        - name: admin-bl-service
          image: $(tag admin-bl-service)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maps-access-service
spec:
  template:
    spec:
      containers:
        - name: maps-access-service
          image: $(tag maps-access-service)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  template:
    spec:
      containers:
        - name: notification-service
          image: $(tag notification-service)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: $(tag frontend)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: $(tag nginx)
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration-runner
spec:
  template:
    spec:
      containers:
        - name: migration-runner
          image: $(tag migration-runner)
EOF

echo "Wrote $PINS_FILE with $IMAGE_VERSION image pins"